# -*- coding: utf-8 -*-
"""Part 1: Algorithms

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPkBxVKZdzySjdn6bTDKpk4O4dw41l8W
"""

def main():
    # Ввод списка чисел
    input_data = input("Введите числа через запятую: ")

    # Преобразуем строку в список целых чисел
    numbers = list(map(int, input_data.split(',')))

    # Четные числа
    even_numbers = [num for num in numbers if num % 2 == 0]
    print(f"Четные числа: {even_numbers}")

    # Максимальное и минимальное число
    max_number = max(numbers)
    min_number = min(numbers)
    print(f"Максимальное число: {max_number}")
    print(f"Минимальное число: {min_number}")

    # Сортировка списка (пузырьковая сортировка)
    sorted_numbers = numbers[:]
    for i in range(len(sorted_numbers)):
        for j in range(len(sorted_numbers) - 1):
            if sorted_numbers[j] > sorted_numbers[j + 1]:
                sorted_numbers[j], sorted_numbers[j + 1] = sorted_numbers[j + 1], sorted_numbers[j]

    print(f"Отсортированный список: {sorted_numbers}")

if __name__ == "__main__":
    main()